name: couchbase
on: push
jobs:
  capella-trial:
    runs-on: ubuntu-latest
    environment: capella-trial
    env:
      ADMINISTRATOR_PASSWORD: ${{secrets.ADMINISTRATOR_PASSWORD}}
      API_SECRET: ${{secrets.API_SECRET}}
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/poetry-buildpack@main
        with:
          tests: tests
          test-entry-point: python test_couchbase.py

