name: mssql
on:
  push:
jobs:
  azure:
    runs-on: ubuntu-latest
    environment: azure
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/setup-odbc@main
      - uses: davidkhala/uv-buildpack@main
        with:
          test-entry-point: pytest sql/mssql/azure_test.py
          extras: mssql
    env:
      MSSQL_PASSWORD: ${{secrets.MSSQL_PASSWORD}}
  testcontainers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/setup-odbc@main
      - uses: davidkhala/uv-buildpack@main
        with:
          test-entry-point: pytest sql/mssql/local_test.py
          extras: mssql mssql-proxy
