name: database
on:
  push:
  workflow_dispatch:

jobs:
  duck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          test-entry-point: python duckdb_test.py
          extras: duck
          groups: duck
  sql:
    strategy:
      matrix:
        db: [mysql, pg, db2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          test-entry-point: pytest sql/${{matrix.db}}_test.py
          extras: ${{matrix.db}}
          groups: sql
  astra:
    runs-on: ubuntu-latest
    environment: astra
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          test-entry-point: pytest cassandra/astra_test.py
          extras: astra
    env:
      TOKEN: ${{secrets.TOKEN}}